spring:
    application.name: config-server
    profiles.active: native
    cloud.config.server.git:
        uri: https://github.com/kuyer/kuyer-sboot/
        searchPaths: kuyer-sboot-config-repo
#        username: 
#        password: 
server.port: 17308
